# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- releases

strategy:
  matrix:
    jdk10_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.10"
    jdk11_windows:
      imageName: "windows-latest"
      jdkVersion: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    echo "Current directory contents:"
    ls -al
    ng build --configuration development
    echo "Directory contents after ng build:"
    ls -al dist/my-app
  displayName: 'npm install and build'
  workingDirectory: my-app
  
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/dist/my-app' # Use the relative path to the root of the repository
    app_build_command: ng build 
    output_location: 'dist/my-app'
    cwd: '$(System.DefaultWorkingDirectory)/my-app'
    azure_static_web_apps_api_token: $(token1)
    deployment_environment: 'developpement'
    platform: 'node'
    runtime_version: '20.x'
    angular.json: angular.json
